name: todoapp
description: "todo list app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
